# Generated by Django 3.2.8 on 2021-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, verbose_name='Serial')),
                ('linha', models.CharField(choices=[('1', 'CTR - CENTRO'), ('2', 'SUL - SUL'), ('3', 'DSL - DIESEL')], max_length=255, verbose_name='Linha')),
                ('horario', models.CharField(choices=[('1', '05-06'), ('2', '06-07'), ('4', '07-08'), ('5', '08-09'), ('6', '09-10'), ('7', '10-11'), ('8', '11-12'), ('9', '12-13'), ('10', '13-14'), ('11', '14-15'), ('12', '15-16'), ('13', '16-17'), ('14', '17-18'), ('15', '18-19'), ('16', '19-20'), ('17', '20-21'), ('18', '21-22'), ('19', '22-23')], max_length=255, verbose_name='Horário')),
                ('adesivo', models.CharField(choices=[('1', 'VERDE'), ('2', 'MARROM'), ('3', 'AZUL')], max_length=255, verbose_name='Adesivo')),
            ],
            options={
                'verbose_name_plural': 'Urnas',
                'unique_together': {('serial',)},
            },
        ),
    ]
